### ISSUE TITLE
crime status API

### ISSUE THREAD

**Issue by wlinnp** [SoundsNeat/AmISafeHere#10]
Create an API which takes in City and State as parameters and return JSON

Use this JSON format as I will parse according to this format in front end. 
Most of them are self-explanatory. 
Line 3: result should set whether true or false. False is set if you cannot find that city in the database. 
Line 5: average can be national average / state average. depends on our discussion. 

For detail statistics, we don't want to display all the years and cram the page with info, so we will just display the latest 3 year. 

{
    "city":"<city name>",
    "state":"<state name>",
    "result":<true/false>,
    "index":<0 to 5>,
    "average":<Double>,
    "years":[
         2014,2013,2012
    ],
    "category":[
         {
             "<name>":[number,number,number]
         },
         <repeat for all crime categories>
    ],
}

**Comment by Lucodivo** [comment]
I will try to get on this tomorrow.

**Comment by Lucodivo** [comment]
Do you need the years in descending order?

We can create the category, but can't you pick the information you want to represent on the front end? Not sure why we would need to change the API to be limited to only three like that.

I mean, I will reduce it for you, if you want. I'm just not sure I see the point.

**Comment by wlinnp** [comment]
My idea was not to show all results. it's too much info. just the last 3 yr, or 5 yr. 
And we probably want them to show in descending order, right? 
And I don't want js to handle that logic. That logic part should be handled by logic (backend). 
---
That's just my idea.

**Comment by Lucodivo** [comment]
I don't care how it's displayed, just how you want to data. If that's how you want it, it should be trivial, so I don't mind.

Aight. That makes sense. Just know that Lake Elsinore only has 5 years of data and it is 2002-2006. So you may still have logic to process if there are any city's with less than 5 or 3 years of data. 

Another thing to note: New York City does not have information on arson. So you need logic to handle if there are no data available for the given categories.

On that note, if there is a category (like arson in NYC) with no data, would you prefer the category be left out of the JSON or that it's data be an empty array?

**Comment by wlinnp** [comment]
For now, don't put empty data

**Comment by Lucodivo** [comment]
You got it, dude.

**Comment by wlinnp** [comment]
Ok. a few comments. 

Currently, the constructor needs city & state. 

The way it works. (may b it's wrong) is we created a Bean Object at the beginning, and whenever it is needed at "Controller", it is called. So we need to rewrite it in a way that we can set City & State separately, and a method to execute which will do the main logic. 

And I saw that the you need space to be replaced with dashes "-". 

I guess the good approach is to specify the input format at the beginning likein javadoc, and whoever calling it should reformat it before calling the method
