### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by bechin** [SoundsNeat/AmISafeHere#13]
It works, but adding features is a headache already.  The flow of the code makes no logical sense.  Related methods sit in different files.  Inputs and outputs are not consistent.

**Comment by wlinnp** [comment]
are you talking about front end or backend?

**Comment by bechin** [comment]
Everything.

**Comment by Lucodivo** [comment]
I did a bunch of refactoring yesterday. I mean one of the CreateCrimeStats is just scraping an html String. It's not really ever going to be pretty and it's not meant to be flexible. We're not writing web page scraping software. We only need to get the data we are extracting.

I was thinking that CreateCrimeStats can be moved into CrimeStats but I hadn't decided if that was the best idea.

**Comment by bechin** [comment]
Problems were resolved significantly after removing example code and conditions further improved gradually over the course of the more recent commits.
