### ISSUE TITLE
Mismatch in indexes of Google's JSON reply

### ISSUE THREAD

**Issue by bechin** [SoundsNeat/AmISafeHere#14]
The JSON objects returned by calls to Google Maps at different times does not return data in a consistent format, causing errors.

**Comment by bechin** [comment]
Found a workaround: using the more-stable "formatted_address" field.

**Comment by wlinnp** [comment]
Unfortunately, that address field is also changing. 
When first accessed, it is return this URL
http://www.city-data.com/city/Westmont-Los-Angeles-Metropolitan-Area.html
when performing auto detection for Pomona, CA, US

**Comment by wlinnp** [comment]
Alright! I found some clues. 
When the error happens, google returns 9 types of addresses. 
When current code works, google returns 8 types. 

Right now, we are trying to get the city, state, country by array index. 

They are changing time to time. What is not changing is the "types" of each of those indexes

"types" : [ "postal_code" ] is the address object which has everything we need and within that, 

"types": [ "locality", "political" ] for city, 

"types" : [ "administrative_area_level_1", "political"  ] for state, 
and 
"types" : [ "country", "political"  ] for country.

**Comment by wlinnp** [comment]
fixed. hopefully it works this time.
