### ISSUE TITLE
Star System to display the result

### ISSUE THREAD

**Issue by wlinnp** [SoundsNeat/AmISafeHere#15]
Beautify the start system with relevant images

**Comment by Lucodivo** [comment]
https://cdn.pixabay.com/photo/2013/07/13/12/16/knife-159519_960_720.png

https://cdn.pixabay.com/photo/2013/07/13/13/42/knife-161412_960_720.png

These should be royalty free.

**Comment by wlinnp** [comment]
used the first knife. 
Can you give me an empty knife to replace the empty star?

**Comment by wlinnp** [comment]
This is a negative approach to indicate how dangerous a city is. 
There should be a vote to decide which approach to use negative / positive.

**Comment by Lucodivo** [comment]
Wai added the solid knife to the project and I created an outline for the blank knife. Currently uses knives to display the danger system. Can be changed back to stars if needed but issue is resolved for now.
