### ISSUE TITLE
Fix Crime Index algorithm

### ISSUE THREAD

**Issue by Lucodivo** [SoundsNeat/AmISafeHere#24]
- Find five model cities
    1. Very Safe
    2. Safe
    3. Neutral
    4. Dangerous
    5. Very Dangerous
- Adjust the algorithm accordingly
- Write JUnit tests that verify that the algorithm is always working correctly for these four cities

**Comment by Lucodivo** [comment]
example. lower (more safe) bounds city to upper (less safe) bounds city

i. Virginia Beach, Virginia to Austin, Texas
ii. Aurora, Colorado to Pittsburgh, Pennsylvania
iii. Tulsa, Oklahoma to Washington D.C.
iv. Atlanta, Georgia to Milwaukee, Wisconsin
v. St. Louis, Missouri to Detroit, Michigan

Ordered using violent crime data from Wikipedia
https://en.wikipedia.org/wiki/List_of_United_States_cities_by_crime_rate

**Comment by jtfetzer** [comment]
Not sure why we need a neutral category, maybe call it average. Right now we have 4 categories, safe, mostly safe, somewhat dangerous, and dangerous. You can change the weights and algorithm if you want, but I'd say don't fix what's not broken. You can create another category for very dangerous, but it seems to me like my algorithm is working, so I wouldn't change it much. I get Virginia Beach 1, Austin 1, Aurora 1, Pittsburgh 3, Tulsa 3, Atlanta 3, Milwaukee 3, St. Louis 4,  Detroit 4. Washington DC throws an error in my old classes, new classes should handle that.

**Comment by Lucodivo** [comment]
I'm not sure if we should even include arson in the crime index. I feel like it's one of the categories that might not exist in the data we extract, and it would effect rural places more than city places.

**Comment by Lucodivo** [comment]
Algorithm can be changed further but it currently works with as this issue had intended it to.
